# Generated by Django 5.0.4 on 2025-03-03 23:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('variety', models.CharField(blank=True, max_length=50, null=True)),
                ('maturity_time', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('germination_time', models.PositiveIntegerField(blank=True, null=True)),
                ('spacing_x', models.PositiveIntegerField(blank=True, null=True)),
                ('spacing_y', models.PositiveIntegerField(blank=True, null=True)),
                ('sun_level', models.CharField(blank=True, choices=[('full sun', 'Fullsun'), ('partial sun', 'Partsun'), ('partial shade', 'Partshade'), ('full shade', 'Fullshade')], max_length=13, null=True)),
                ('planting_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_req', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('plant_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('role', models.CharField(choices=[('admin', 'Ad'), ('user', 'Us'), ('moderator', 'Mo')], default='user', max_length=9, verbose_name='role')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='zip code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gardens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('size_x', models.PositiveIntegerField()),
                ('size_y', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Garden_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_date', models.DateField(default=datetime.date.today)),
                ('x_coordinate', models.PositiveIntegerField()),
                ('y_coordinate', models.PositiveIntegerField()),
                ('garden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.gardens')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_value', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('planting_depth__gte', models.Q(('planting_depth__isnull', True)))), name='check_depth_pos'),
        ),
        migrations.AddConstraint(
            model_name='plants',
            constraint=models.CheckConstraint(check=models.Q(('water_req__gte', models.Q(('water_req__isnull', True)))), name='check_water_pos'),
        ),
        migrations.AddField(
            model_name='garden_log',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.plants'),
        ),
        migrations.AddField(
            model_name='replies',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.forums'),
        ),
        migrations.AddField(
            model_name='replies',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.replies'),
        ),
        migrations.AddField(
            model_name='replies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='reply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.replies'),
        ),
        migrations.AddConstraint(
            model_name='gardens',
            constraint=models.CheckConstraint(check=models.Q(('size_x__gt', 0)), name='check_size_x_pos'),
        ),
        migrations.AddConstraint(
            model_name='gardens',
            constraint=models.CheckConstraint(check=models.Q(('size_y__gt', 0)), name='check_size_y_pos'),
        ),
        migrations.AddConstraint(
            model_name='garden_log',
            constraint=models.UniqueConstraint(fields=('garden_id', 'x_coordinate', 'y_coordinate'), name='unq_plot_space'),
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('user_id', 'reply_id'), name='unq_vote'),
        ),
    ]
=======
    ]
>>>>>>> jb-datafetching
