# Generated by Django 5.0.4 on 2025-03-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plants',
            options={'verbose_name': 'plant', 'verbose_name_plural': 'plants'},
        ),
    ]
