# Generated by Django 5.0.4 on 2025-03-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_forums_options_alter_garden_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='forum_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.forums'),
        ),
    ]
