# Generated by Django 5.0.4 on 2025-04-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_user_updated_at_alter_user_created_at_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='epantherid',
        # ),
    ]
