# Generated by Django 5.2 on 2025-04-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0015_remove_user_epantherid'),
    ]

    operations = [
       # migrations.RemoveField(
       #     model_name='user',
       #     name='epantherid',
       # ),
    ]
