# Generated by Django 5.0.4 on 2025-04-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_remove_user_epantherid'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='epantherid',
        # ),
    ]
