# Generated by Django 5.0.4 on 2025-04-03 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='garden',
            name='gardens_check_size_x_pos',
        ),
        migrations.RemoveConstraint(
            model_name='garden',
            name='gardens_check_size_y_pos',
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.CheckConstraint(check=models.Q(('size_x__gt', 0)), name='check_size_x_pos'),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.CheckConstraint(check=models.Q(('size_y__gt', 0)), name='check_size_y_pos'),
        ),
    ]
