# Generated by Django 5.0.4 on 2025-04-18 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_alter_garden_options_and_mor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='garden',
        #     name='check_size_x_pos',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='garden',
        #     name='check_size_y_pos',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='gardenlog',
        #     name='unique_plot_space',
        # ),
        migrations.AlterUniqueTogether(
            name='gardenlog',
            unique_together={('garden', 'x_coordinate', 'y_coordinate')},
        ),
        migrations.AlterField(
            model_name='gardenlog',
            name='garden',
            field=models.ForeignKey(help_text='The garden to which this log belongs', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gardens.garden'),
        ),
        migrations.AlterField(
            model_name='gardenlog',
            name='health_status',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Healthy', 'Healthy'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Dying', 'Dying'), ('Dead', 'Dead'), ('Unknown', 'Unknown')], default='Healthy', help_text='Current health status of the plant', max_length=15, verbose_name='Health Status'),
        ),
        migrations.AlterField(
            model_name='gardenlog',
            name='x_coordinate',
            field=models.PositiveIntegerField(help_text='X position in the garden grid (0-based)', verbose_name='X Position'),
        ),
        migrations.AlterField(
            model_name='gardenlog',
            name='y_coordinate',
            field=models.PositiveIntegerField(help_text='Y position in the garden grid (0-based)', verbose_name='Y Position'),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.CheckConstraint(check=models.Q(('size_x__gt', 0)), name='check_size_x_coordinate'),
        ),
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.CheckConstraint(check=models.Q(('size_y__gt', 0)), name='check_size_y_coordinate'),
        ),
        migrations.RemoveField(
            model_name='gardenlog',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='gardenlog',
            name='y_position',
        ),
    ]
