# Generated by Django 5.0.4 on 2025-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_remove_garden_check_size_x_pos_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='garden',
        #     name='check_size_x_pos',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='garden',
        #     name='check_size_y_pos',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='gardenlog',
        #     name='unique_plot_space',
        # ),
        migrations.AlterField(
            model_name='gardenlog',
            name='x_coordinate',
            field=models.PositiveIntegerField(help_text='X coordinate in the garden grid (0-based)', verbose_name='X Coordinate'),
        ),
        migrations.AlterField(
            model_name='gardenlog',
            name='y_coordinate',
            field=models.PositiveIntegerField(help_text='Y coordinate in the garden grid (0-based)', verbose_name='Y Coordinate'),
        ),
    ]
