# Generated by Django 5.0.4 on 2025-04-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_remove_garden_check_size_x_pos_and_more'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='garden',
        #     name='check_size_x_pos',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='garden',
        #     name='check_size_y_pos',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='gardenlog',
        #     name='unique_plot_space',
        # ),
        migrations.AddField(
            model_name='gardenlog',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Flag for soft deletion'),
        ),
    ]
