# Generated by Django 5.2 on 2025-04-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_remove_garden_check_size_x_pos_and_more'),
    ]

    operations = [
       # migrations.RemoveConstraint(
       #     model_name='garden',
       #     name='check_size_x_pos',
       # ),
       # migrations.RemoveConstraint(
       #     model_name='garden',
       #     name='check_size_y_pos',
       # ),
       # migrations.RemoveConstraint(
       #     model_name='gardenlog',
       #     name='unique_plot_space',
       # ),
    ]
