# Generated by Django 5.0.4 on 2025-04-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('unknown', 'Unknown')], default='unknown', help_text='Acceptance status of the plant name', max_length=20),
        ),
    ]
