# Generated by Django 5.0.4 on 2025-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='watering_interval',
        ),
        migrations.AddField(
            model_name='plant',
            name='water_interval',
            field=models.PositiveIntegerField(default=7, help_text='Recommended days between watering'),
        ),
    ]
