# Generated by Django 5.0.4 on 2025-04-18 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plantchangerequest_plant_fertilizing_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['common_name'], name='idx_plant_common_name'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['created_by'], name='idx_plant_created_by'),
        ),
    ]
