# Generated by Django 5.2 on 2025-04-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_idx_plant_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='days_to_harvest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average number of days from planting to harvest', max_digits=6, null=True),
        ),
    ]
