# Generated by Django 5.0.4 on 2025-04-18 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0002_remove_garden_gardens_check_size_x_pos_and_more'),
        ('plants', '0004_plantchangerequest_plant_fertilizing_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('Prune', 'Pr'), ('Fertilize', 'Fe'), ('Harvest', 'Ha'), ('Water', 'Wa'), ('Other', 'Ot')], max_length=9)),
                ('subtype', models.CharField(blank=True, help_text='Additional categorization for custom notifications', max_length=25, verbose_name='notification subtype')),
                ('interval', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this notification was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this notification was last updated')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.garden')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPlantAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
            options={
                'unique_together': {('notification', 'plant')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='plants',
            field=models.ManyToManyField(through='notifications.NotificationPlantAssociation', to='plants.plant'),
        ),
        migrations.CreateModel(
            name='NotificationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_completed', models.DateTimeField(blank=True, null=True)),
                ('next_due', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='notifications.notification')),
            ],
            options={
                'ordering': ['next_due'],
                'indexes': [models.Index(fields=['next_due'], name='notificatio_next_du_b91887_idx'), models.Index(fields=['status'], name='notificatio_status_9ed477_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(check=models.Q(('interval__gt', 0)), name='check_interval'),
        ),
    ]
