# Generated by Django 5.0.4 on 2025-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(help_text='Name of the notification', max_length=255),
        ),
    ]
