# Generated by Django 5.0.4 on 2025-04-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Prune', 'Pr'), ('Fertilize', 'Fe'), ('Harvest', 'Ha'), ('Water', 'Wa'), ('Weather', 'We'), ('Other', 'Ot')], max_length=9),
        ),
    ]
