# Generated by Django 5.0.4 on 2025-04-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationinstance',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the notification was completed', null=True),
        ),
        migrations.AddField(
            model_name='notificationinstance',
            name='message',
            field=models.TextField(blank=True, help_text='Content of the notification', null=True),
        ),
    ]
