# Generated by Django 5.0.4 on 2025-04-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationinstance_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PR', 'Prune'), ('FE', 'Fertilize'), ('HA', 'Harvest'), ('WA', 'Water'), ('WE', 'Weather'), ('OT', 'Other')], max_length=9),
        ),
    ]
